const glassProducts = [
    {
        id: 1,
        name: "Saint-Gobain Clear Float Glass",
        category: "Float Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 85,
        minOrderQty: 50,
        description: "High-quality clear float glass suitable for windows and general applications",
        tags: ["window", "residential", "commercial", "clear"]
    },
    {
        id: 2,
        name: "AIS Tempered Safety Glass",
        category: "Tempered Glass",
        thickness: 10,
        width: 2000,
        height: 3000,
        color: "clear",
        coating: "Low-E",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "AIS Glass",
        pricePerSqm: 180,
        minOrderQty: 25,
        description: "Heat-strengthened tempered glass with Low-E coating for energy efficiency",
        tags: ["safety", "energy", "window", "commercial"]
    },
    {
        id: 3,
        name: "Gujarat Guardian Laminated Glass",
        category: "Laminated Glass",
        thickness: 12,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "UV Protection",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "SGCC"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 320,
        minOrderQty: 20,
        description: "Two-layer laminated glass with PVB interlayer for enhanced safety and UV protection",
        tags: ["safety", "uv", "commercial", "balcony"]
    },
    {
        id: 4,
        name: "Asahi India Double Glazed IGU",
        category: "IGU",
        thickness: 24,
        width: 1200,
        height: 1200,
        color: "clear",
        coating: "Low-E Double",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "ENERGY STAR"],
        supplier: "Asahi India Glass",
        pricePerSqm: 450,
        minOrderQty: 15,
        description: "Insulated glass unit with 6mm Low-E glass and 12mm argon gap for thermal insulation",
        tags: ["energy", "thermal", "window", "residential"]
    },
    {
        id: 5,
        name: "Saint-Gobain Bronze Tinted Float Glass",
        category: "Float Glass",
        thickness: 8,
        width: 2440,
        height: 3660,
        color: "bronze",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 110,
        minOrderQty: 50,
        description: "Bronze tinted float glass for solar control and aesthetic applications",
        tags: ["tinted", "solar", "commercial", "architectural"]
    },
    {
        id: 6,
        name: "AIS Frosted Tempered Glass",
        category: "Tempered Glass",
        thickness: 12,
        width: 1500,
        height: 2400,
        color: "frosted",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "AIS Glass",
        pricePerSqm: 220,
        minOrderQty: 20,
        description: "Acid-etched frosted tempered glass for privacy applications",
        tags: ["privacy", "frosted", "office", "partition"]
    },
    {
        id: 7,
        name: "Gujarat Guardian Silver Mirror",
        category: "Mirror",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "silver",
        coating: "copper-free",
        edgeFinish: "grinded",
        certifications: ["IS 1370", "CE", "ISO 9001"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 150,
        minOrderQty: 30,
        description: "High-quality silver mirror with copper-free backing for durability",
        tags: ["mirror", "interior", "bathroom", "decorative"]
    },
    {
        id: 8,
        name: "Asahi Aluminium Sliding Door Hardware",
        category: "Aluminium Hardware",
        thickness: 2,
        width: 2400,
        height: 2100,
        color: "anodized silver",
        coating: "powder coated",
        edgeFinish: "smooth",
        certifications: ["IS 6173", "CE", "ISO 9001"],
        supplier: "Asahi India Glass",
        pricePerSqm: 280,
        minOrderQty: 10,
        description: "Complete aluminium sliding door system with handles, locks, and tracks",
        tags: ["hardware", "door", "sliding", "aluminium"]
    },
    {
        id: 9,
        name: "Saint-Gobain Low-E IGU",
        category: "IGU",
        thickness: 20,
        width: 1800,
        height: 2100,
        color: "clear",
        coating: "Soft Low-E",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "ENERGY STAR"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 380,
        minOrderQty: 15,
        description: "Double glazed unit with soft coat Low-E for superior thermal performance",
        tags: ["energy", "thermal", "window", "low-e"]
    },
    {
        id: 10,
        name: "AIS Blue Tinted Tempered Glass",
        category: "Tempered Glass",
        thickness: 8,
        width: 2000,
        height: 3000,
        color: "blue",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "AIS Glass",
        pricePerSqm: 195,
        minOrderQty: 25,
        description: "Blue tinted tempered glass for architectural and decorative applications",
        tags: ["tinted", "decorative", "commercial", "safety"]
    },
    {
        id: 11,
        name: "Gujarat Guardian Acoustic Laminated Glass",
        category: "Laminated Glass",
        thickness: 10,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "Acoustic PVB",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "STC"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 380,
        minOrderQty: 20,
        description: "Acoustic laminated glass with special PVB for sound reduction",
        tags: ["acoustic", "sound", "office", "partition"]
    },
    {
        id: 12,
        name: "Asahi India Clear Float Glass",
        category: "Float Glass",
        thickness: 5,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Asahi India Glass",
        pricePerSqm: 75,
        minOrderQty: 100,
        description: "Standard 5mm clear float glass for general glazing applications",
        tags: ["window", "residential", "budget", "clear"]
    },
    {
        id: 13,
        name: "Saint-Gobain Aluminium Window Frame",
        category: "Aluminium Hardware",
        thickness: 3,
        width: 1500,
        height: 1800,
        color: "white powder coated",
        coating: "powder coated",
        edgeFinish: "smooth",
        certifications: ["IS 6173", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 220,
        minOrderQty: 10,
        description: "Aluminium window frame system with gaskets and hardware",
        tags: ["hardware", "window", "frame", "aluminium"]
    },
    {
        id: 14,
        name: "AIS Heat Reflective Glass",
        category: "Float Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "reflective",
        coating: "Solar Control",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "AIS Glass",
        pricePerSqm: 125,
        minOrderQty: 50,
        description: "Heat reflective float glass with solar control coating",
        tags: ["solar", "reflective", "energy", "commercial"]
    },
    {
        id: 15,
        name: "Gujarat Guardian Decorative Mirror",
        category: "Mirror",
        thickness: 5,
        width: 1220,
        height: 2440,
        color: "bronze",
        coating: "tinted backing",
        edgeFinish: "polished",
        certifications: ["IS 1370", "CE", "ISO 9001"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 165,
        minOrderQty: 25,
        description: "Bronze tinted decorative mirror for interior design applications",
        tags: ["mirror", "decorative", "tinted", "interior"]
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = glassProducts;
}

// Log for testing
console.log('Generated', glassProducts.length, 'products');
console.log('Sample product:', glassProducts[0]);
