// Global products array for AmalGus Smart Glass Marketplace
window.products = [
    {
        id: 1,
        name: "Saint-Gobain Clear Float Glass",
        category: "Float Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 85,
        minOrderQty: 50,
        description: "High-quality clear float glass suitable for windows and general applications",
        tags: ["window", "residential", "commercial", "clear"]
    },
    {
        id: 2,
        name: "AIS Clear Float Glass",
        category: "Float Glass",
        thickness: 4,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "AIS Glass",
        pricePerSqm: 75,
        minOrderQty: 100,
        description: "Standard 4mm clear float glass for residential windows and partitions",
        tags: ["window", "residential", "budget", "clear"]
    },
    {
        id: 3,
        name: "Gujarat Guardian Bronze Tinted Float Glass",
        category: "Float Glass",
        thickness: 8,
        width: 2440,
        height: 3660,
        color: "bronze",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 110,
        minOrderQty: 50,
        description: "Bronze tinted float glass for solar control and aesthetic applications",
        tags: ["tinted", "solar", "commercial", "architectural"]
    },
    {
        id: 4,
        name: "Asahi India Green Float Glass",
        category: "Float Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "green",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Asahi India Glass",
        pricePerSqm: 95,
        minOrderQty: 50,
        description: "Green tinted float glass for decorative and architectural applications",
        tags: ["tinted", "decorative", "architectural", "green"]
    },
    {
        id: 5,
        name: "ModiGuard Low-E Float Glass",
        category: "Float Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "Low-E",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ENERGY STAR"],
        supplier: "ModiGuard",
        pricePerSqm: 120,
        minOrderQty: 50,
        description: "Energy-efficient Low-E coated float glass for green building projects",
        tags: ["energy", "low-e", "residential", "commercial"]
    },
    {
        id: 6,
        name: "Gold Plus Reflective Float Glass",
        category: "Float Glass",
        thickness: 8,
        width: 2440,
        height: 3660,
        color: "silver",
        coating: "reflective",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Gold Plus Glass",
        pricePerSqm: 130,
        minOrderQty: 50,
        description: "Silver reflective float glass for solar control and privacy in commercial buildings",
        tags: ["reflective", "solar", "privacy", "commercial"]
    },
    {
        id: 7,
        name: "Saint-Gobain Frosted Float Glass",
        category: "Float Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "frosted",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 100,
        minOrderQty: 50,
        description: "Acid-etched frosted float glass for privacy and decorative applications",
        tags: ["privacy", "decorative", "office", "bathroom"]
    },
    {
        id: 8,
        name: "AIS Blue Tinted Float Glass",
        category: "Float Glass",
        thickness: 10,
        width: 2440,
        height: 3660,
        color: "blue",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "AIS Glass",
        pricePerSqm: 125,
        minOrderQty: 50,
        description: "Blue tinted float glass for decorative and architectural applications",
        tags: ["tinted", "decorative", "architectural", "blue"]
    },
    {
        id: 9,
        name: "Gujarat Guardian Wire Mesh Glass",
        category: "Float Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 120,
        minOrderQty: 50,
        description: "Wired mesh glass for fire resistance and security applications",
        tags: ["fire", "security", "industrial", "safety"]
    },
    {
        id: 10,
        name: "Asahi India Grey Float Glass",
        category: "Float Glass",
        thickness: 8,
        width: 2440,
        height: 3660,
        color: "grey",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Asahi India Glass",
        pricePerSqm: 105,
        minOrderQty: 50,
        description: "Grey tinted float glass for modern architectural applications",
        tags: ["tinted", "architectural", "modern", "grey"]
    },
    {
        id: 11,
        name: "ModiGuard Ultra Clear Float Glass",
        category: "Float Glass",
        thickness: 12,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "ModiGuard",
        pricePerSqm: 160,
        minOrderQty: 30,
        description: "Ultra-clear low-iron float glass for premium architectural applications",
        tags: ["premium", "architectural", "clear", "luxury"]
    },
    {
        id: 12,
        name: "Gold Plus Obsidian Float Glass",
        category: "Float Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "black",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Gold Plus Glass",
        pricePerSqm: 140,
        minOrderQty: 50,
        description: "Black tinted float glass for dramatic architectural statements",
        tags: ["tinted", "decorative", "architectural", "black"]
    },
    {
        id: 13,
        name: "Saint-Gobain Self-Cleaning Float Glass",
        category: "Float Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "self-cleaning",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 180,
        minOrderQty: 30,
        description: "Self-cleaning coated float glass for low-maintenance applications",
        tags: ["maintenance", "commercial", "clear", "innovative"]
    },
    {
        id: 14,
        name: "AIS Heat Reflective Float Glass",
        category: "Float Glass",
        thickness: 10,
        width: 2440,
        height: 3660,
        color: "gold",
        coating: "heat-reflective",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "AIS Glass",
        pricePerSqm: 145,
        minOrderQty: 50,
        description: "Gold heat-reflective float glass for tropical climate applications",
        tags: ["solar", "tropical", "commercial", "energy"]
    },
    {
        id: 15,
        name: "Gujarat Guardian Patterned Float Glass",
        category: "Float Glass",
        thickness: 4,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "grinded",
        certifications: ["IS 2835", "CE", "ISO 9001"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 90,
        minOrderQty: 100,
        description: "Patterned float glass for decorative privacy applications",
        tags: ["decorative", "privacy", "residential", "patterned"]
    },
    {
        id: 16,
        name: "AIS Tempered Safety Glass",
        category: "Tempered Glass",
        thickness: 10,
        width: 2000,
        height: 3000,
        color: "clear",
        coating: "Low-E",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "AIS Glass",
        pricePerSqm: 180,
        minOrderQty: 25,
        description: "Heat-strengthened tempered glass with Low-E coating for energy efficiency",
        tags: ["safety", "energy", "window", "commercial"]
    },
    {
        id: 17,
        name: "Saint-Gobain Tempered Glass",
        category: "Tempered Glass",
        thickness: 12,
        width: 1500,
        height: 2400,
        color: "clear",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 200,
        minOrderQty: 20,
        description: "High-strength tempered glass for shower enclosures and partitions",
        tags: ["safety", "shower", "partition", "residential"]
    },
    {
        id: 18,
        name: "Gujarat Guardian Tempered Glass",
        category: "Tempered Glass",
        thickness: 8,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "UV Protection",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 165,
        minOrderQty: 25,
        description: "UV-protected tempered glass for balcony railings and outdoor applications",
        tags: ["safety", "uv", "balcony", "outdoor"]
    },
    {
        id: 19,
        name: "Asahi India Frosted Tempered Glass",
        category: "Tempered Glass",
        thickness: 12,
        width: 1500,
        height: 2400,
        color: "frosted",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "Asahi India Glass",
        pricePerSqm: 220,
        minOrderQty: 25,
        description: "Frosted tempered glass for privacy and safety in bathroom and office partitions",
        tags: ["privacy", "office", "partition", "safety"]
    },
    {
        id: 20,
        name: "ModiGuard Blue Tinted Tempered Glass",
        category: "Tempered Glass",
        thickness: 10,
        width: 2000,
        height: 3000,
        color: "blue",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "ModiGuard",
        pricePerSqm: 195,
        minOrderQty: 25,
        description: "Blue tinted tempered glass for decorative and architectural applications",
        tags: ["tinted", "decorative", "architectural", "safety"]
    },
    {
        id: 21,
        name: "Gold Plus Frameless Shower Glass",
        category: "Tempered Glass",
        thickness: 12,
        width: 1000,
        height: 2000,
        color: "clear",
        coating: "hydrophobic",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "Gold Plus Glass",
        pricePerSqm: 250,
        minOrderQty: 10,
        description: "Frameless shower enclosure glass with water-repellent coating",
        tags: ["shower", "residential", "waterproof", "safety"]
    },
    {
        id: 22,
        name: "Saint-Gobain Bronze Tempered Glass",
        category: "Tempered Glass",
        thickness: 8,
        width: 2140,
        height: 3660,
        color: "bronze",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 175,
        minOrderQty: 25,
        description: "Bronze tinted tempered glass for solar control and safety applications",
        tags: ["tinted", "solar", "safety", "commercial"]
    },
    {
        id: 23,
        name: "AIS Low-E Tempered Glass",
        category: "Tempered Glass",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "clear",
        coating: "Low-E",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "AIS Glass",
        pricePerSqm: 190,
        minOrderQty: 25,
        description: "Energy-efficient Low-E tempered glass for sustainable building projects",
        tags: ["energy", "low-e", "sustainable", "safety"]
    },
    {
        id: 24,
        name: "Gujarat Guardian Curved Tempered Glass",
        category: "Tempered Glass",
        thickness: 10,
        width: 1800,
        height: 3000,
        color: "clear",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 280,
        minOrderQty: 15,
        description: "Custom curved tempered glass for architectural facades and canopies",
        tags: ["curved", "architectural", "facade", "custom"]
    },
    {
        id: 25,
        name: "Asahi India Heat-Soaked Tempered Glass",
        category: "Tempered Glass",
        thickness: 12,
        width: 1500,
        height: 2400,
        color: "clear",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "Asahi India Glass",
        pricePerSqm: 240,
        minOrderQty: 20,
        description: "Heat-soaked tempered glass for critical safety applications",
        tags: ["safety", "critical", "commercial", "premium"]
    },
    {
        id: 26,
        name: "ModiGuard Laminated Tempered Glass",
        category: "Tempered Glass",
        thickness: 16,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "ModiGuard",
        pricePerSqm: 320,
        minOrderQty: 15,
        description: "Laminated tempered glass for maximum safety and security",
        tags: ["safety", "security", "laminated", "premium"]
    },
    {
        id: 27,
        name: "Gold Plus Digital Printed Tempered Glass",
        category: "Tempered Glass",
        thickness: 10,
        width: 2000,
        height: 3000,
        color: "clear",
        coating: "printed",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "Gold Plus Glass",
        pricePerSqm: 260,
        minOrderQty: 20,
        description: "Digital printed tempered glass for decorative and branding applications",
        tags: ["decorative", "printed", "branding", "custom"]
    },
    {
        id: 28,
        name: "Saint-Gobain Fire-Rated Tempered Glass",
        category: "Tempered Glass",
        thickness: 12,
        width: 1500,
        height: 2400,
        color: "clear",
        coating: "fire-resistant",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1", "UL 10C"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 290,
        minOrderQty: 15,
        description: "Fire-rated tempered glass for commercial building safety",
        tags: ["fire", "safety", "commercial", "rated"]
    },
    {
        id: 29,
        name: "AIS Tinted Tempered Glass",
        category: "Tempered Glass",
        thickness: 8,
        width: 2140,
        height: 3660,
        color: "green",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "ANSI Z97.1"],
        supplier: "AIS Glass",
        pricePerSqm: 185,
        minOrderQty: 25,
        description: "Green tinted tempered glass for solar control and decorative applications",
        tags: ["tinted", "solar", "decorative", "safety"]
    },
    {
        id: 30,
        name: "Gujarat Guardian Bullet Resistant Tempered Glass",
        category: "Tempered Glass",
        thickness: 25,
        width: 1200,
        height: 2400,
        color: "clear",
        coating: "none",
        edgeFinish: "polished",
        certifications: ["IS 2553", "CE", "NIJ Level III"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 850,
        minOrderQty: 5,
        description: "Bullet resistant tempered glass for high-security applications",
        tags: ["security", "bullet", "high-security", "premium"]
    },
    {
        id: 31,
        name: "Gujarat Guardian Clear Laminated Glass",
        category: "Laminated Glass",
        thickness: 10,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "SGCC"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 280,
        minOrderQty: 20,
        description: "Clear laminated glass offering superior safety and acoustic performance",
        tags: ["safety", "acoustic", "commercial", "office"]
    },
    {
        id: 32,
        name: "Saint-Gobain Laminated Safety Glass",
        category: "Laminated Glass",
        thickness: 12,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "UV Protection",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "SGCC"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 320,
        minOrderQty: 20,
        description: "Two-layer laminated glass with PVB interlayer for enhanced safety and UV protection",
        tags: ["safety", "uv", "commercial", "balcony"]
    },
    {
        id: 33,
        name: "AIS Acoustic Laminated Glass",
        category: "Laminated Glass",
        thickness: 16,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "acoustic",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "SGCC"],
        supplier: "AIS Glass",
        pricePerSqm: 380,
        minOrderQty: 20,
        description: "Special acoustic laminated glass for sound insulation in noisy environments",
        tags: ["acoustic", "sound", "commercial", "office"]
    },
    {
        id: 34,
        name: "Asahi India Tinted Laminated Glass",
        category: "Laminated Glass",
        thickness: 12,
        width: 2140,
        height: 3660,
        color: "bronze",
        coating: "none",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "SGCC"],
        supplier: "Asahi India Glass",
        pricePerSqm: 340,
        minOrderQty: 20,
        description: "Bronze tinted laminated glass for solar control and safety applications",
        tags: ["tinted", "solar", "safety", "commercial"]
    },
    {
        id: 35,
        name: "ModiGuard Low-E Laminated Glass",
        category: "Laminated Glass",
        thickness: 14,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "Low-E",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "ENERGY STAR"],
        supplier: "ModiGuard",
        pricePerSqm: 360,
        minOrderQty: 20,
        description: "Energy-efficient Low-E laminated glass for sustainable building projects",
        tags: ["energy", "low-e", "sustainable", "safety"]
    },
    {
        id: 36,
        name: "Gold Plus Decorative Laminated Glass",
        category: "Laminated Glass",
        thickness: 10,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "interlayer",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "SGCC"],
        supplier: "Gold Plus Glass",
        pricePerSqm: 300,
        minOrderQty: 20,
        description: "Decorative interlayer laminated glass for interior design applications",
        tags: ["decorative", "interior", "design", "safety"]
    },
    {
        id: 37,
        name: "Saint-Gobain Hurricane Resistant Laminated Glass",
        category: "Laminated Glass",
        thickness: 18,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "none",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "ASTM E1996"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 450,
        minOrderQty: 15,
        description: "Hurricane resistant laminated glass for coastal and high-wind areas",
        tags: ["hurricane", "coastal", "safety", "premium"]
    },
    {
        id: 38,
        name: "AIS Security Laminated Glass",
        category: "Laminated Glass",
        thickness: 20,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "security",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "EN 1063"],
        supplier: "AIS Glass",
        pricePerSqm: 520,
        minOrderQty: 10,
        description: "Multi-layer security laminated glass for high-security applications",
        tags: ["security", "multi-layer", "high-security", "premium"]
    },
    {
        id: 39,
        name: "Asahi India Fire Resistant Laminated Glass",
        category: "Laminated Glass",
        thickness: 16,
        width: 2140,
        height: 3660,
        color: "clear",
        coating: "fire-resistant",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "UL 10C"],
        supplier: "Asahi India Glass",
        pricePerSqm: 420,
        minOrderQty: 15,
        description: "Fire resistant laminated glass for commercial building safety",
        tags: ["fire", "safety", "commercial", "rated"]
    },
    {
        id: 40,
        name: "Gujarat Guardian Colored Laminated Glass",
        category: "Laminated Glass",
        thickness: 12,
        width: 2140,
        height: 3660,
        color: "blue",
        coating: "none",
        edgeFinish: "flat",
        certifications: ["IS 2554", "CE", "SGCC"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 350,
        minOrderQty: 20,
        description: "Blue colored laminated glass for decorative and architectural applications",
        tags: ["colored", "decorative", "architectural", "safety"]
    },
    {
        id: 41,
        name: "Asahi India Double Glazed IGU",
        category: "IGU",
        thickness: "5+12+5",
        width: 1200,
        height: 1200,
        color: "clear",
        coating: "Low-E Double",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "ENERGY STAR"],
        supplier: "Asahi India Glass",
        pricePerSqm: 450,
        minOrderQty: 15,
        description: "Insulated glass unit with 5mm Low-E glass and 12mm argon gap for thermal insulation",
        tags: ["energy", "thermal", "window", "residential"]
    },
    {
        id: 42,
        name: "Saint-Gobain Triple Glazed IGU",
        category: "IGU",
        thickness: "6+12+6+12+6",
        width: 1000,
        height: 1000,
        color: "clear",
        coating: "Low-E Triple",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "PASSIVE HOUSE"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 680,
        minOrderQty: 10,
        description: "Triple glazed insulated unit with two Low-E coatings for maximum thermal performance",
        tags: ["energy", "thermal", "luxury", "residential"]
    },
    {
        id: 43,
        name: "AIS Tinted IGU",
        category: "IGU",
        thickness: "6+12+6",
        width: 1200,
        height: 1200,
        color: "bronze",
        coating: "Low-E Tinted",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "ENERGY STAR"],
        supplier: "AIS Glass",
        pricePerSqm: 480,
        minOrderQty: 15,
        description: "Bronze tinted insulated glass unit for solar control and thermal insulation",
        tags: ["solar", "tinted", "energy", "commercial"]
    },
    {
        id: 44,
        name: "Gujarat Guardian Acoustic IGU",
        category: "IGU",
        thickness: "8+16+8",
        width: 1200,
        height: 1200,
        color: "clear",
        coating: "Acoustic",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "STC 40"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 550,
        minOrderQty: 15,
        description: "Acoustic insulated glass unit for sound insulation in noisy environments",
        tags: ["acoustic", "sound", "commercial", "office"]
    },
    {
        id: 45,
        name: "Asahi India Low-E IGU",
        category: "IGU",
        thickness: "4+12+4",
        width: 1200,
        height: 1200,
        color: "clear",
        coating: "Low-E Single",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "ENERGY STAR"],
        supplier: "Asahi India Glass",
        pricePerSqm: 420,
        minOrderQty: 15,
        description: "Standard Low-E insulated glass unit for residential and commercial applications",
        tags: ["energy", "low-e", "standard", "versatile"]
    },
    {
        id: 46,
        name: "Saint-Gobain Self-Cleaning IGU",
        category: "IGU",
        thickness: "6+12+6",
        width: 1200,
        height: 1200,
        color: "clear",
        coating: "Self-Cleaning",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 580,
        minOrderQty: 15,
        description: "Self-cleaning insulated glass unit for low-maintenance applications",
        tags: ["maintenance", "cleaning", "innovative", "commercial"]
    },
    {
        id: 47,
        name: "AIS Security IGU",
        category: "IGU",
        thickness: "10+16+10",
        width: 1200,
        height: 1200,
        color: "clear",
        coating: "Laminated",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "EN 1063"],
        supplier: "AIS Glass",
        pricePerSqm: 750,
        minOrderQty: 10,
        description: "Security insulated glass unit with laminated glass for enhanced protection",
        tags: ["security", "laminated", "protection", "premium"]
    },
    {
        id: 48,
        name: "Gujarat Guardian Argon Filled IGU",
        category: "IGU",
        thickness: "6+16+6",
        width: 1200,
        height: 1200,
        color: "clear",
        coating: "Low-E Argon",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "ENERGY STAR"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 520,
        minOrderQty: 15,
        description: "Argon gas filled insulated glass unit for superior thermal performance",
        tags: ["argon", "thermal", "energy", "performance"]
    },
    {
        id: 49,
        name: "Asahi India Reflective IGU",
        category: "IGU",
        thickness: "6+12+6",
        width: 1200,
        height: 1200,
        color: "silver",
        coating: "Reflective",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "ISO 9001"],
        supplier: "Asahi India Glass",
        pricePerSqm: 490,
        minOrderQty: 15,
        description: "Reflective insulated glass unit for solar control and privacy",
        tags: ["reflective", "solar", "privacy", "commercial"]
    },
    {
        id: 50,
        name: "Saint-Gobain Curved IGU",
        category: "IGU",
        thickness: "8+16+8",
        width: 1000,
        height: 1500,
        color: "clear",
        coating: "Low-E Curved",
        edgeFinish: "sealed",
        certifications: ["IS 3370", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 850,
        minOrderQty: 10,
        description: "Custom curved insulated glass unit for architectural applications",
        tags: ["curved", "architectural", "custom", "premium"]
    },
    {
        id: 51,
        name: "Gujarat Guardian Bronze Mirror",
        category: "Mirror",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "bronze",
        coating: "tinted",
        edgeFinish: "polished",
        certifications: ["IS 1370", "CE", "ISO 9001"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 165,
        minOrderQty: 25,
        description: "Bronze tinted decorative mirror for interior design applications",
        tags: ["mirror", "decorative", "tinted", "interior"]
    },
    {
        id: 52,
        name: "Saint-Gobain Silver Mirror",
        category: "Mirror",
        thickness: 5,
        width: 2440,
        height: 3660,
        color: "silver",
        coating: "standard",
        edgeFinish: "polished",
        certifications: ["IS 1370", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 145,
        minOrderQty: 25,
        description: "Standard silver mirror for residential and commercial applications",
        tags: ["mirror", "standard", "residential", "commercial"]
    },
    {
        id: 53,
        name: "AIS Antique Mirror",
        category: "Mirror",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "antique",
        coating: "distressed",
        edgeFinish: "polished",
        certifications: ["IS 1370", "CE", "ISO 9001"],
        supplier: "AIS Glass",
        pricePerSqm: 180,
        minOrderQty: 25,
        description: "Antique distressed mirror for vintage and classic interior designs",
        tags: ["mirror", "antique", "vintage", "decorative"]
    },
    {
        id: 54,
        name: "Gold Plus Colored Mirror",
        category: "Mirror",
        thickness: 5,
        width: 2440,
        height: 3660,
        color: "blue",
        coating: "colored",
        edgeFinish: "polished",
        certifications: ["IS 1370", "CE", "ISO 9001"],
        supplier: "Gold Plus Glass",
        pricePerSqm: 175,
        minOrderQty: 25,
        description: "Blue colored mirror for decorative and contemporary interior designs",
        tags: ["mirror", "colored", "contemporary", "decorative"]
    },
    {
        id: 55,
        name: "Asahi India Safety Mirror",
        category: "Mirror",
        thickness: 6,
        width: 2440,
        height: 3660,
        color: "silver",
        coating: "safety-backing",
        edgeFinish: "polished",
        certifications: ["IS 1370", "CE", "ANSI Z97.1"],
        supplier: "Asahi India Glass",
        pricePerSqm: 195,
        minOrderQty: 25,
        description: "Safety backed mirror for commercial and public space applications",
        tags: ["mirror", "safety", "commercial", "public"]
    },
    {
        id: 56,
        name: "Saint-Gobain Aluminium Sliding Door Hardware",
        category: "Aluminium Hardware",
        thickness: "N/A",
        width: "N/A",
        height: "N/A",
        color: "silver",
        coating: "anodized",
        edgeFinish: "brushed",
        certifications: ["IS 1661", "CE", "ISO 9001"],
        supplier: "Saint-Gobain Glass India",
        pricePerSqm: 85,
        minOrderQty: 10,
        description: "Premium aluminium sliding door hardware system for frameless glass doors",
        tags: ["hardware", "sliding", "door", "aluminium"]
    },
    {
        id: 57,
        name: "AIS Glass Fittings Kit",
        category: "Aluminium Hardware",
        thickness: "N/A",
        width: "N/A",
        height: "N/A",
        color: "black",
        coating: "powder-coated",
        edgeFinish: "matte",
        certifications: ["IS 1661", "CE", "ISO 9001"],
        supplier: "AIS Glass",
        pricePerSqm: 65,
        minOrderQty: 20,
        description: "Complete glass fittings kit for shower enclosures and partitions",
        tags: ["hardware", "fittings", "shower", "accessories"]
    },
    {
        id: 58,
        name: "Gujarat Guardian Spider Fittings",
        category: "Aluminium Hardware",
        thickness: "N/A",
        width: "N/A",
        height: "N/A",
        color: "silver",
        coating: "polished",
        edgeFinish: "mirror",
        certifications: ["IS 1661", "CE", "ISO 9001"],
        supplier: "Gujarat Guardian",
        pricePerSqm: 120,
        minOrderQty: 15,
        description: "Spider glass fittings for structural glass facades and canopies",
        tags: ["hardware", "spider", "facade", "structural"]
    },
    {
        id: 59,
        name: "ModiGuard Glass Railing System",
        category: "Aluminium Hardware",
        thickness: "N/A",
        width: "N/A",
        height: "N/A",
        color: "bronze",
        coating: "anodized",
        edgeFinish: "brushed",
        certifications: ["IS 1661", "CE", "ISO 9001"],
        supplier: "ModiGuard",
        pricePerSqm: 95,
        minOrderQty: 20,
        description: "Complete aluminium railing system for glass balustrades and railings",
        tags: ["hardware", "railing", "balustrade", "safety"]
    },
    {
        id: 60,
        name: "Gold Plus Glass Patch Fittings",
        category: "Aluminium Hardware",
        thickness: "N/A",
        width: "N/A",
        height: "N/A",
        color: "silver",
        coating: "satin",
        edgeFinish: "brushed",
        certifications: ["IS 1661", "CE", "ISO 9001"],
        supplier: "Gold Plus Glass",
        pricePerSqm: 75,
        minOrderQty: 25,
        description: "Patch fittings for frameless glass partitions and shower enclosures",
        tags: ["hardware", "patch", "frameless", "partition"]
    }
];

console.log('Loaded', window.products.length, 'products for AmalGus marketplace');
